paths:
  /api/permissions:
    get:
      summary: Get all permissions
      tags: [Permission]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of permissions

    post:
      summary: Create a new permission
      tags: [Permission]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - permissionName
                - permissionDescription
              properties:
                permissionName:
                  type: string
                permissionDescription:
                  type: string
      responses:
        '201':
          description: Permission created

  /api/permissions/{id}:
    get:
      summary: Get a permission by ID
      tags: [Permission]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Found
        '404':
          description: Not found

    put:
      summary: Update a permission by ID
      tags: [Permission]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                permissionName:
                  type: string
                permissionDescription:
                  type: string
      responses:
        '200':
          description: Updated

    delete:
      summary: Delete a permission by ID
      tags: [Permission]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted
