paths:
  /api/designations:
    get:
      tags:
        - UserDesignation
      summary: Get all user designations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user designations
    post:
      tags:
        - UserDesignation
      summary: Create a new user designation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDesignationInput'
      responses:
        '201':
          description: Created successfully
        '400':
          description: Validation error

  /api/designations/{id}:
    get:
      tags:
        - UserDesignation
      summary: Get a user designation by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User designation found
        '404':
          description: Not found
    put:
      tags:
        - UserDesignation
      summary: Update a user designation by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDesignationInput'
      responses:
        '200':
          description: Updated successfully
        '400':
          description: Validation error
        '404':
          description: Not found
    delete:
      tags:
        - UserDesignation
      summary: Delete a user designation by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted successfully
        '404':
          description: Not found

components:
  schemas:
    UserDesignationInput:
      type: object
      required:
        - designationName
        - description
        - permissions
      properties:
        designationName:
          type: string
          example: manager
        description:
          type: string
          example: Manager - Team lead and management role
        permissions:
          type: array
          items:
            type: string
          example:
            - "6846c97983c8f1a80fb7f606"
            - "6846c98883c8f1a80fb7f610"
            - "6846c99483c8f1a80fb7f61a"
