paths:
  /api/users:
    get:
      tags:
        - User
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
    post:
      tags:
        - User
      summary: Create a new user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created

  /api/users/{id}:
    get:
      tags:
        - User
      summary: Get a user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
    put:
      tags:
        - User
      summary: Update a user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateInput'
      responses:
        '200':
          description: User updated
    delete:
      tags:
        - User
      summary: Delete a user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted

components:
  schemas:
    UserInput:
      type: object
      required:
        - username
        - userEmail
        - userDesignation
        - userCompany
        - userPassword
        - userPhno
      properties:
        username:
          type: string
          example: johndoe
        userEmail:
          type: string
          example: johndoe@example.com
        userDesignation:
          type: string
          example: 665a12345678bcdef0123456
        userCompany:
          type: string
          example: Acme Corp
        userPassword:
          type: string
          example: securePassword123
        userPhno:
          type: string
          example: "9876543210"

    UserUpdateInput:
      type: object
      properties:
        username:
          type: string
        userEmail:
          type: string
        userDesignation:
          type: string
        userCompany:
          type: string
        userPassword:
          type: string
        userPhno:
          type: string
